server:
  servlet:
    context-path: "/api"
spring:
  datasource:
    url: ${SPRING_DATASOURCE_USERNAME}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  jpa:
    show-sql: true
  liquibase:
    change-log: "db/changelog/liquibase.xml"
jwt:
  key: ${JWT_KEY}
  access-token-expiration: 3600000
  refresh-token-expiration: 86400000
